# Generated by Django 3.2 on 2021-04-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='destination_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stations', to='core.station', verbose_name='Станция назначения'),
        ),
        migrations.AlterField(
            model_name='station',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.organization', verbose_name='Организация владелец'),
        ),
    ]
