# Generated by Django 3.2 on 2021-04-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210427_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='station',
            name='destination_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stations', to='core.station', verbose_name='Станция назначения'),
        ),
    ]
