# Generated by Django 3.2 on 2021-04-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contract_counterparty_counterpartytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='address',
            field=models.CharField(max_length=512, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='inn',
            field=models.CharField(max_length=512, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='ogrn',
            field=models.CharField(max_length=512, null=True, verbose_name='ОГРН'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='u_address',
            field=models.CharField(max_length=512, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='name',
            field=models.CharField(max_length=512, unique=True, verbose_name='Юридическое наименование'),
        ),
        migrations.AlterField(
            model_name='counterparty',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, to='core.CounterPartyType', verbose_name='Вид'),
        ),
    ]
