# Generated by Django 3.2 on 2021-04-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210427_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписания'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.organization', verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='contract',
            name='end_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания действия'),
        ),
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=512, null=True, unique=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='contract',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.counterparty', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала действия'),
        ),
    ]
