# Generated by Django 3.2 on 2021-04-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210427_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='subscribe_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подписания'),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
    ]
