# Generated by Django 3.2 on 2021-04-27 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210427_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.contract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Предмет договора',
                'verbose_name_plural': 'Предметы оговора',
            },
        ),
    ]
