# Generated by Django 3.2 on 2021-04-27 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contractobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид топлива',
                'verbose_name_plural': 'Виды топлива',
            },
        ),
        migrations.CreateModel(
            name='StationToFuelBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('invite_reason', models.CharField(max_length=64)),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.fueltype')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.station')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contractobject',
            options={'verbose_name': 'Предмет договора', 'verbose_name_plural': 'Предметы договора'},
        ),
        migrations.AddField(
            model_name='contractobject',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.fueltype', verbose_name='Вид топлива'),
        ),
        migrations.AddField(
            model_name='station',
            name='fuel_types',
            field=models.ManyToManyField(blank=True, through='core.StationToFuelBalance', null=True, to='core.FuelType', verbose_name='Виды топлива'),
        ),
    ]
