# Generated by Django 3.2 on 2021-05-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_stationtofuelbalance_invite_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Наименование')),
                ('fuel_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='marks', to='core.fueltype', verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Марка топлива',
                'verbose_name_plural': 'Марки топлива',
            },
        ),
    ]
