# Generated by Django 3.2 on 2021-05-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210505_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractobject',
            name='name',
        ),
    ]
