# Generated by Django 3.2 on 2021-05-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_statusrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
    ]
