# Generated by Django 3.2 on 2021-05-08 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_operation_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='waybill',
            name='contract_object',
        ),
        migrations.AddField(
            model_name='operation',
            name='contract_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.contractobject', verbose_name='Объект договора'),
        ),
    ]
