# Generated by Django 3.2 on 2021-05-10 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_writeoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waybill',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='waybills', to='core.operation', verbose_name='Операция'),
        ),
    ]
